library(dplyr)
data<-read.table("household_power_consumption.txt",sep=";",header=T,na.strings="?",stringsAsFactors=F)
data<-data%>%filter(Date=="1/2/2007"|Date=="2/2/2007")%>%
 mutate(date_time=paste(Date,Time))%>% select(-(Date:Time))
data$date_time<-strptime(data$date_time,"%d/%m/%Y %H:%M:%S")
png(file="plot3.png")
with(data,plot(date_time,Sub_metering_1,type="l",xlab="",ylab="Energy sub metering"))
 with(data,lines(date_time,Sub_metering_2,col="red"))
  with(data,lines(date_time,Sub_metering_3,col="blue"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1))
dev.off()